### DISCUSSION TITLE
Improve the user experience in order to show the command before being executed

### DISCUSSION THREAD

**Discussion by diegolovison** [Hyperfoil/qDup#231] [General]
Create the following script
```yaml
scripts:
  ensure-quarkus-cli:
  - sh: quarkus version #to see if the command exists
  getting-started:
  - sh: cd /tmp/
  - sh: "[[ ! -d quarkus-quickstarts ]] && git clone https://github.com/quarkusio/quarkus-quickstarts.git" # prevent cloning again
  - sh: cd quarkus-quickstarts
  - sh: cd getting-started
  - script: ensure-quarkus-cli
  - sh: quarkus dev
hosts:
  test: dlovison@localhost
roles:
  setup-env:
    hosts:
    - test
    run-scripts:
    - getting-started
```
Run it with `-ix` in order to ignore the `quarkus-quickstarts` folder presented on the disk.

The output will be:

https://github.com/user-attachments/assets/1d252e4a-694c-4f0b-a02f-ce045454c8ed

This will give the impression that the qDup is hanging.
In practice, it is running `quarkus dev` without printing anything in the terminal.

I would like:
* print the command before being executed
* being able to capture `quarkus dev` output and display it in the terminal

What does the community think about that?
I spent some hours until I figured it out.

**Comment by diegolovison** [comment]
Here is other example
```yaml
scripts:
  hello-qdup:
    - sh: "ping -c 30 redhat.com"
hosts:
  local : ${{target-host}}
roles:
  run-hello-qdup:
    hosts:
      - local
    run-scripts:
      - hello-qdup
```
Output:
```
14:00:22.763 starting 1 scripts
14:00:22.765 hello-qdup:16@localhost: script-cmd: hello-qdup
14:00:22.766 hello-qdup:16@localhost: hello-qdup
14:01:02.902 hello-qdup:16@localhost: ping -c 30 redhat.com
PING redhat.com (34.235.198.240) 56(84) bytes of data.

--- redhat.com ping statistics ---
30 packets transmitted, 0 received, 100% packet loss, time 29721ms
```
It will be in the console only when the ping has finished.
