### ISSUE TITLE
if command to shorten conditional steps

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#100]
While it is possible to use conditions using inline bash like this
```
- sh: if [ "${{FOO}}" == "foo" ]; then ./foo; else ./bar; fi
```
this gets troublesome to read. qDup would deserve built-in if that would do the same (even evaluating the condition using `test`/`[`), but structured as
```
- if: "${{FOO}}" == "foo"
  then:
  - sh: ./foo
  else:
  - sh: ./bar
```

**Comment by willr3** [comment]
you can do something similar with `read-state` and an evaluating state pattern `${{=` which executes as javascript
```yaml
- read-state: ${{='${{FOO}}' === 'foo' }}
  then:
    - sh: ./foo
  else:
  - sh: ./bar
```
Note the quotes around `'${{FOO}}'` otherwise the javascript execution will look for a variable with the name of whatever is in `${{FOO}}`.
Do we think qDup needs an alias `if` for the `read-state: ${{=....}}` or should I add this to the `read-state` docs as an example?
