### ISSUE TITLE
confusing regex syntax

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#101]
Incorrect indentation of `then` is accepted by qDup but it is never fired. qDup should error out with this.
```
- sh: <some command>
  watch:
  - regex:
      pattern: foobar
      then:
      - abort: I hate foobars!
```
