### ISSUE TITLE
Watch with alternative

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#103]
With watch-regexp pattern I would like to fire signal when the regexp is matched but abort/do something else when it never occurs. I can't find a convenient way to do that/test if the signal was fired.

```
- sh: ...
  watch:
  - regex: foobar
    then:
    - signal: FOO
    ifNeverMatched:
    - abort: No foos found.
```

**Comment by willr3** [comment]
You can do that with a `read-signal` and `else`
```yaml
- sh: dosomething.sh
  watch:
  - regex: foobar
    then:
    - signal: FOO
- read-signal: FOO
  else:
  - abort: FOO never signaled
```
but there is a challenge with `signal` under `watch`. qDup will calculate the expected number of invocations to `signal` before `wait-for` are executed based on the number of scripts and the number of times `signal` occurs with the same name but that won't work if the `signal` is invoked for multiple lines of output from `dosomething.sh` If the `FOO` signal should only occur after the 2nd line containing `foobar` then we need to add a `set-signal: FOO 2` before the `sh`. This will tell qDup to considered `FOO` signalled after the second time `signal: FOO` is executed.
