### ISSUE TITLE
Print output from watch

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#106]
When a command is executed with `watch` the output is not shown in the log. Even worse, the command itself is not printed either.

While qDup is filtering the output it should also print it (unless explicitly disabled). With shell based scripts it's possible to pipe the command through `tee` and record the output in a log, but that option is not available inside CLIs. This makes it hard to debug problems in watched commands.

**Comment by willr3** [comment]
Can you provide the sample yaml that is not outputting as expected? qDup commands write their output to console / file after they finish executing.
```yaml
- sh: dosomething.sh
  watch:
  - regex: foobar
    then:
    - signal: FOO
```
the `regex` in this example will only write to output if it matches because otherwise the log will be flooded with regex output for each line of output from `dosomething.sh` If you want to see each line of output from `dosomething.sh` as it occurs we can update the example with an `echo`
```yaml
- sh: dosomething.sh
  watch:
  - echo
  - regex: foobar
    then:
    - signal: FOO
```
The `regex` will write output if the pattern misses and there is an `else` that runs if the pattern misses.
```yaml
- sh: dosomething.sh
  watch:
  - regex: foobar
    then:
    - signal: FOO
    else:
    - log: message
```
