### ISSUE TITLE
Signals inside read-state -> regex -> script commands are not processed correctly

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#116]
Given a sample script

```
scripts:

  single:
    - log: single
    - signal: sig

  replicated:
    - log: replicated
    - signal: sig

  caller: 
    - log: caller
    - read-state: ${{TOPOLOGY}}
      then:
        - regex: single
          then:
            - script: single
        - regex: multi
          then:
            - script: replicated

  waiter:
    - log: waiting for signal
    - wait-for: sig
hosts:
  local: me@localhost

roles:
  role:
    hosts: [local]
    run-scripts:
    - caller
    - waiter

states:
  TOPOLOGY: single
```

I would expect the `sig` signal to be called once, by either the `single` script, or the `replicated` script depending on the parameter passed to state variable `TOPOLOGY`.  However, the signal is raised twice.

A test case that tests this behaviour is here: https://github.com/johnaohara/qDup/commit/3638a7d648c00620b53d46f7dd4e03fe85113bb5
