### ISSUE TITLE
State value is not populated when scripts are called dynamically

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#117]
If a script is called dynamically via a state variable, e.g.:
```
scripts:
  some_script:
    - log: Some log Message
roles:
  test-runner:
    hosts:
      - server-host
    run-scripts:
      - ${{RUN_SCRIPT}}
states:
  RUN_SCRIPT: some_script
```

The run.log entries do not have the script name populated, e.g.

```
12:23:05.161 ${{RUN_SCRIPT}}@server01: Some log Message
```

The script name should be populated, i.e.

```
12:23:05.161 some_script@server01: Some log Message
```
