### ISSUE TITLE
Container Hosts

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/qDup#165]
We talked about using containers for the target host, which sounds great. Let's iron out the details. 

### feature ideas:
* connect to a container that is already running (local and remote)
I have this working in a POC. We use `docker exec` to start a shell process (`/bin/bash`) and treat it like a normal terminal connection.
* start a new container based on an image url (local and remote)
this is also working in a POC using `podman run --detach`. qDup normally creates a new ssh session for setup, each run script, then cleanup. This means if we are starting a new container based on an image we have to track the containerId. We could make the `Host` mutable and store it there.
* stop the container after the run?
there is an internal `postRun` phase for writing the `run.json` that we could use to stop and remove containers. qDup does not open connections during that phase but we could add it.
* remove the container after the run?
we can use the same `postRun` connection to cleanup the containers
* remove the container if the run `aborts`?
I could see us wanting to save the pods for inspection after an aborted run but I could also see that turning into a mess.
* support different container platforms (podman, docker, kubernetes, openshift, etc)?
we could support this by either having an enum of supported platforms and storing the setup commands internally or we directly expose the setup commands. If we use the enum option we will need a way to support login (e.g. `oc login`). If we directly expose the setup commands we would have:
1. `checkContainerId` - check if a containerId already exists and is running
2. `checkContainerName` - check if a named container already exists and is running
3. `startContainer` - start a container based on an image
4. `connectShell` - connect to a shell in the container
5. `upload` - send a file to the container
6. `download` - download a file from the container
7. `stopContainer` - stop a running container
8. `removeContainer` - remove the container
9. `platformLogin` - do we have a separate login command or do users need to use `oc login ...; `  before each command?
These would all support `${{...}}` pattern replacement to access run state (for oc login injection) and have a `containerId` state variable passed in from qDup.

### yaml
we should have a syntax to express the host in one line as well as the mapping syntax. The one line syntax does not need to support all the options but we use it extensively in the tests. I think it will be easy enough to identify a container name but there could be corner cases if the name includes an `@`.
```yaml
host:
  justImage: quay.io/foo/bar #implies local
  justContainerId: b3a7bc64f5ad #normal host notation would have an @ so we assume it is container
  localContainerId: !local/b3a7bc64f5ad #local would be implied but can also be explicitly set
  remoteContainerId: user@server/b3a7bc64f5ad #a we pares for an @ then a / to determine there is both host and container info
  justContainerName: bold_rhodes #same as above but we have to check containerId then name for existing containers
  localImage: !local/quay.io/foo/bar # do we use / to separate host info from container info?
  remoteImage: user@server/quay.io/foo/bar 
```    

### local changes
we use `rsync` or `scp` to copy files from the SUT to the run output folder. Those won't work to get files out of a container. I think we will have to store the `upload` and `download` commands on the `host` and use the current commands as defaults.

Any ideas, comments, concerns?

**Comment by rvansa** [comment]
Initially I thought that the containers would have to run `sshd` inside and you would connect normally over ssh, but using just `podman exec ... bash` is definitely more usable, though it's more work on the qDup side.

I see little value in connecting to an already running container, I wouldn't support this in qDup. Either you want to do some part of the setup in containers, so qDup starts them and then tears them down, but expecting a container to be running, hardcoding the container IDs and such is not the idiomatic way. For hacks, the user can `podman exec ...` into himself.
Looking forward to hear about use cases where a setup that expect the container to run would make sense.

I would stop and remove the container after the test by default, for debugging an override should be possible with
```
myContainer:
   image: quay.io/foo/bar
   stop: true
   remove: false
```

Please don't start values with exclamation mark, the example
```
localImage: !local/quay.io/foo/bar 
```
actually maps an empty value tagged with tag `!local/quay.io/foo/bar`. Have you used `!local` for the local-mode already?
