### ISSUE TITLE
Ctrl-C on signal

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#19]
I'd like to run a command until a signal is fired:

```yaml
- sh: perf record -a
  - await: FABAN_RAMP_DOWN
  - ctrlC
```

**Comment by rvansa** [comment]
An alternative could be:
```yaml
- sh: {
  command: perf record -a
  background: true
  save-pid: PERF_PID
}
- waitFor: FABAN_RAMP_DOWN
- sh: kill ${{PERF_PID}}
```

**Comment by willr3** [comment]
We can run 
```yaml
- sh: perf record -a > /tmp/out.log 2 > /tmp/err.log & export PID="$!"
```
This will put `PID` into the environment for the current script. If we need to share the value with another script
```yaml
- sh: perf record -a > /tmp/out.log 2 > /tmp/err.log & export PID="$!"
- sh: echo ${PID}
  - set-state: RUN.SHARED_PID
```
I like the idea of waiting for a signal while a command is running in the foreground because that is what we normally do with multiple terminals. Now we have `on-signal`
```yaml
- sh: perf record -a
  on-signal:
    FABAN_RAMP_DOWN:
    - ctrlC
```
We can also use `read-signal` which will only invoke its children commands if the signal is already reached
```yaml
- sh: perf record -a
  on-signal:
    FABAN_RAMP_DOWN:
    - read-signal: SOMETHING_BAD
      then:
      - ctrlC
```
That last example uses the new yaml (actual yaml) syntax based on an overloaded MapConstructor
