### ISSUE TITLE
Using containers causes the java process to hang after the run completes

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/qDup#209]
The jar does not exit when a host starts a container on either the `LOCAL` or a remote connection.  The run completes, the json server stops, to pod stops, but the process does not exit.

recreate script
```
scripts:
  foo:
  - sh: uname -a
  - sh: echo "foo" > foo.txt
  - queue-download: foo.txt
  - sh: ls -al
  - sh: date

hosts:
  target:
    local: true
    platform: docker
    container: quay.io/fedora/fedora

roles:
  run:
    hosts: [target]
    setup-scripts:
    - foo
 ```
