### ISSUE TITLE
qDup process hangs when using a remote container host

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/qDup#212]
Similar to #209 where the process would hang on a local container shell but this time it hangs for a remote shell.

```
scripts:
  foo:
  - sh: uname -a
  - sh: echo "foo" > foo.txt
  - queue-download: foo.txt
  - sh: ls -al
  - sh: date

hosts:
  target:
    username: me
    hostname: localhost
    platform: docker
    container: quay.io/fedora/fedora:40

roles:
  run:
    hosts: [target]
    setup-scripts:
    - foo
```
