### ISSUE TITLE
Insufficient cores leading to a deadlock or application hang

### ISSUE THREAD

**Issue by diegolovison** [Hyperfoil/qDup#229]
The application utilizes a `Semaphore` referred to as `blockingSemaphore` to control a shared resource.

**AbstractShell.java**
```java
if(seconds > 0){
  acquired = blockingSemaphore.tryAcquire(seconds,TimeUnit.SECONDS);
} else {
    blockingSemaphore.acquire();//released in the observer
}
```
```java
blockingConsumer = (response) -> {
    blockingResponse.setLength(0);
    blockingResponse.append(response);
    blockingSemaphore.release();
};
```

The `ScheduledThreadPoolExecutor` is configured with a limited number of cores.
Previous code: `new ScheduledThreadPoolExecutor(Runtime.getRuntime().availableProcessors()/2,new ThreadFactory() {`
New code: `new ScheduledThreadPoolExecutor(getMinimumScheduleCorePoolSize(),new ThreadFactory() {`
```java
private static int getMinimumScheduleCorePoolSize() {
    int cores = Runtime.getRuntime().availableProcessors() / 2;
    if (cores < 3) {
        return 3;
    } else {
        return cores;
    }
}
```
The `blockingSemaphore.acquire()` and `blockingSemaphore.release()` are both created by the `ScheduledThreadPoolExecutor` mentioned above.

A situation like the following will hang if `corePoolSize` of the `ScheduledThreadPoolExecutor` is equal to 2.
```yaml
scripts:
  doit:
    - sh: date
      then:
        - set-state: RUN.date
  update:
    - sh: echo 'uno' >> /tmp/foo.txt
    - sleep: 2s
    - sh: echo 'dos' >> /tmp/foo.txt
    - sleep: 2s
    - sh: echo 'tres' >> /tmp/foo.txt
    - set-state: RUN.update true
  foo:
    - sleep: 15s
    - sh: tail -f /tmp/foo.txt
      watch:
        - regex: dos
          then:
            - script:
                name: doit
                async: true
        - regex: tres
          then:
            - ctrlC
    - set-state: RUN.foo true
hosts:
  local: "<Insert host value here>"
roles:
  doit:
    hosts: [local]
    run-scripts: [update, foo]
```
If the number of cores is equals 2 (`new ScheduledThreadPoolExecutor(2,new ThreadFactory() {`) and you run the YAML above, two threads will be in the `blockingSemaphore.acquire()` state. Because of that, there is no space for the third thread calls the `blockingSemaphore.release()` and the application will hang forever.

Increasing the number of cores (e.g., to 3) resolves the issue temporarily but introduces the potential for another scenario where three cores couldn't call the `blockingSemaphore.acquire()`, leading to a hang. This approach merely postpones the issue without addressing its root cause.
