### ISSUE TITLE
invoke: <script> WITH state not populating state variables

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#38]
A script with;
```
  run-tests:
    - invoke: run-test
        WITH:
          REPO: myRepo
```
state variables are not being populated in run-test script ${{REPO}} is null
