### ISSUE TITLE
Enabled variable substitution in hosts configuration section

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#40]
Enable variable substitution in host section, so that hosts can be defined dynamically via command line, e.g.;

```
...
hosts:
  server: user@${{SERVER_HOST:server.some.domain.com}}:22
  databaseuser@${{DB_HOST:database.some.domain.com}}:22

states:
  SERVER_HOST: 
  DB_HOST: 
```

Will allow calling qDup with;

```
java -jar {PATH}/qDup.jar -b /tmp ./qdup.yaml  -S SERVER_HOST=192.168.0.1 -S DB_HOST=192.168.0.2
```
