### ISSUE TITLE
Malformed yaml causes runtime errors

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#5]
I was missing a colon after `upload` in
```yaml
scripts:
  send-run-xml:
    - upload ${{ENV.SCRIPT_DIR}}/assets/run.xml ${{FABAN_CONFIG}}
  restart-database:
    ...
```
which resulted in `yaml.json` that looked like
```json
[
  [
    {
      "lineNumber": 1,
      "value": "istio - web profile",
      "key": "name"
    },
    {
      "lineNumber": 2,
      "key": "scripts",
      "child": [[{
        "lineNumber": 4,
        "key": "send-run-xml",
        "child": [[{
          "dashed": true,
          "lineNumber": 5,
          "key": "upload"
        }]]
      }]]
    },
    {
      "lineNumber": 5,
      "key": "${{ENV.SCRIPT_DIR}}/assets/run.xml"
    },
    {
      "lineNumber": 5,
      "key": "${{FABAN_CONFIG}}",
      "child": [[
        {
          "lineNumber": 7,
          "key": "restart-database",
          "child": [
            [{
              "dashed": true,
              "lineNumber": 8,
              "value": "/root/bin/resetdb-stable.sh -s",
              "key": "sh"
            }]
```
And the config builder failed as some signals were not found. This would deserve better error handling.
