### ISSUE TITLE
Enhancment - multiline sh cmd shorthand

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#53]
It would be nice if qDup could support multi line -sh cmd's so that only one `- sh:` entry is in the yaml file, but qDup automatically expands multi-line definitions to multilpe -sh cmds.

e.g. a definition like this;

```
      - sh: cd ${{DIR_ROOT}}
      - sh: [[ -d ${{DIR_ROOT}}/${{DIR}} ]] ; rm -rf ${{DIR_ROOT}}/${{DIR}}
      - sh: git clone ${{GIT_URL}}
      - sh: cd ${{DIR}}
      - sh: sed -i 's/SOMETHING=30/SOMETHING=1/g' ./someScript.sh
```

becomes;

```
      - sh: |
            cd ${{DIR_ROOT}}
            [[ -d ${{DIR_ROOT}}/${{DIR}} ]] ; rm -rf ${{DIR_ROOT}}/${{DIR}}
            git clone ${{GIT_URL}}
            cd ${{DIR}}
            sed -i 's/SOMETHING=30/SOMETHING=1/g' ./someScript.sh
```

**Comment by willr3** [comment]
I ran a test where I included multiple bash commands in a single `sh` and it ran all the commands. There are a few problems:
- All of the output is grouped together as though it were a single command
- The input commands are not removed from the output because qdup looks for the commands as a single string
- The prompt is seen between each command in the output
What do you think should behave differently?

**Comment by johnaohara** [comment]
I was thinking that qDup could expand that snytax into multiple `sh` commands, so that it provides a shorthand for writing a list of `sh` commands without the issues that you mention above

**Comment by willr3** [comment]
I'm not sure this is something we could add on top of the yaml syntax because there are already use cases where mult-line `sh` needs to remain a single command to the remote shell.
```yaml
    - sh: |
        oc apply <<EOF -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: perf-test-ns${{index}}
        EOF
```
I find this a useful way to create a file with injected state values and without having to rely on uploading a template file and using sed but there are other instances of multi-line shell input that we would need to differentiate.
One option might be to support an array in addition to the string value.
```yaml
    - sh:
        - cd ${{DIR_ROOT}}
        - [[ -d ${{DIR_ROOT}}/${{DIR}} ]] ; rm -rf ${{DIR_ROOT}}/${{DIR}}
        - git clone ${{GIT_URL}}
        - cd ${{DIR}}
        - sed -i 's/SOMETHING=30/SOMETHING=1/g' ./someScript.sh
```
This would cut down on some of the repetition but we would still have the `- ` prefix before the lines. There is also a map use case when specifying `silent` or in-line `prompts`
```yaml
    - sh:
        command:
            - cd ${{DIR_ROOT}}
            - ...
        silent: true
        prompt:
            "Password: " : 12345
````
Do we think `command` should accept an array like `sh`? If so, does `silent` and `prompt` apply to all of the entries in the `command` array? I would suspect the answer should be yes.
