### ISSUE TITLE
Scripts invoked in loops are called twice per loop

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#55]
where I define a loop such as;

```
      capture-cpu-stats:
       - for-each: BUILD ${{BUILDS}}
         then:
          - for-each: PIPELINE_SIZE ${{PIPELINE_SIZES}}
            then:
             - for-each: POOL_SIZE ${{POOL_SIZES}}
               then:
                - for-each: PROFILE ${{PROLFILING}}
                  then:
                  - script: dstat
                    with: 
                      WAIT_START: ${{BUILD.tag}}-${{PIPELINE_SIZE}}-${{POOL_SIZE}}-${{PROFILE.name}}-WRK-MEASURE-START
                      WAIT_STOP: ${{BUILD.tag}}-${{PIPELINE_SIZE}}-${{POOL_SIZE}}-${{PROFILE.name}}-WRK-DONE
                      DSTAT_FILE: /tmp/cpu/${{BUILD.tag}}-${{PIPELINE_SIZE}}-${{POOL_SIZE}}-${{PROFILE.name}}.dstat.out
```

that calls dstat script;

```
   dstat: # WAIT_START WAIT_STOP
     - sh: rm -f /tmp/dstat.log #-f because @#%$^! root and the rm -i alias
     - wait-for: ${{WAIT_START:}}
     - sh: dstat -Tcdngym 1 > ${{DSTAT_FILE:/tmp/dstat.log}} & export DSTAT_PID="$!"
     - wait-for: ${{WAIT_STOP}}
     - sh: kill ${DSTAT_PID}
     - queue-download: ${{DSTAT_FILE:/tmp/dstat.log}}
```

The dstat script is invoked once for the first iteration of the loop, but twice on every subsequent iteration of the loop
