### ISSUE TITLE
Provide ability to define state variables as secret

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#56]
At present, state variables are resolved at runtime and written to the console, e.g.

```
scripts:
   testSecret:
      - sh: echo "${{SOME_SECRET}}"
...
states:
   SOME_SECRET: mySecretPassword!!
```

Would output the following;

```
12:19:48.046 testSecret@server:echo "mySecretPassword!!"
mySecretPassword!!
```

Users should be able to denote that a state variable is a secret, and should not be written to the console

e.g.
```
scripts:
   testSecret:
      - sh: echo "${{SOME_SECRET}}"
...
states:
   *SOME_SECRET: mySecretPassword!!
```

Would output;

```
12:19:48.046 testSecret@server:echo "****"
****
```

Secrets could be passed into qDup via the command line, e.g.

```
$ java -jar qDup.jar -B /tmp/run /path/to/qdup.yaml -S SOME_SECRET=p4ssw0rd! 
```
