### ISSUE TITLE
Script defaults

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#60]
In async-profiler I've found that you use `${{GIT_REPO:/tmp/async-profiler}}` multiple times. You also declare used variables in a comment - that leads me to a suggestion that the script could be written as:

```yaml
name: async-profiler
defaults:
  GIT_REPO: /tmp/async-profiler
required:
- ROOT_PASSWORD
- ...
scripts: ...
```

and qDup would make sure that the required variables are set and non-empty and optionally set defaults on the non-mandatory ones.

**Comment by johnaohara** [comment]
I think it is a good idea to stop repetition in scripts. 

State variables can currently be defined with a default value and overridden at runtime.  
e.g.

```yaml
states:
  BUILD_PROJECT: false
```

I think the important change here is to be able to define if the variable is required or not and thrown an exception if the state variable has not been defined either in the script or at runtime.

 Perhaps we could have an extra field available when defining a state variable that determines if the variable is required and deprecate the default state values that can currently be defined at the point in the script that a state variable is resolved? 

e.g.

```yaml
states:
  BUILD_PROJECT: 
    - value: false
    - required: true
  BUILD_PROJECT_EMPTY: 
    - value:
    - required: true
```
The second definition would cause an exception if BUILD_PROJECT_EMPTY was not passed a value at runtime

@willr3 wdyt?

**Comment by rvansa** [comment]
You don't need to put `value`/`required into a list.

I agree that while it might be more verbose (repetition of `value` and `required`) it's probably better to have single mapping for variables than two mappings (`defaults` and `required` as I suggested above). Note that setting value for required state does not make much sense, so you can contract that to

```yaml
states:
  VAR_WITH_DEFAULT: some-default
  ANOTHER_VAR:
    default: foobar # Just an alternative way to set default
  REQUIRED_VAR:
    required: true # or maybe optional: false?
```

**Comment by rvansa** [comment]
@johnaohara Btw. yesterday we've discussed with Will that in order to have the states configurable either from bash script (e.g. in CLI) or from qDup script it would be nice to ignore `-S FOO=${FOO}` when `${FOO}` is empty, instead of overriding value in script with an empty value. We could intentionally unset FOO using `-S !FOO` (though I doubt that will be required much in practice).

**Comment by johnaohara** [comment]
> ```yaml
> states:
>   VAR_WITH_DEFAULT: some-default
>   ANOTHER_VAR:
>     default: foobar # Just an alternative way to set default
>   REQUIRED_VAR:
>     required: true # or maybe optional: false?
> ```

This example is similar to how steps can have multiple key/value mappings with some keys having default values and I think makes the most sense.
If we default optional to false, this would retain the current behaviour

**Comment by johnaohara** [comment]
> @johnaohara Btw. yesterday we've discussed with Will that in order to have the states configurable either from bash script (e.g. in CLI) or from qDup script it would be nice to ignore `-S FOO=${FOO}` when `${FOO}` is empty, instead of overriding value in script with an empty value. We could intentionally unset FOO using `-S !FOO` (though I doubt that will be required much in practice).

+1

**Comment by willr3** [comment]
I created #61 for the change to `-S` so that we don't override values with an empty string.
We could replace all the `${{GIT_REPO:/tmp/async-profiler}}` with a `set-state` at the start of the script
```yaml
scripts:
  foo:
  - set-state: repo ${{GIT_REPO:/tmp/async-profiler}}
  - sh: echo ${{repo}} #do stuff with repo instead of GIT_REPO
```
I probably put too much weight on the copy paste crutch when creating the initial scripts :)
After eb1054e59f3c05effecac38eddb085a863bd14be the run should abort if `${{FOO}}` fails to resolve to a state value so we have to use `${{FOO:}}` if the script supports an empty value. Please let me know if that isn't happening somewhere :)
```yaml
- set-state: script_foo ${{FOO:}} #optional value
- set-state: script_bar ${{BAR}} #required value, aborts run if missing
```
I think runs aborting due to missing state should already provide the desired check on required state so we don't need to add reserved words to the state json. Aborting has the added benefit of catching runtime issues that cannot be detected at compile time. For example `set-state: ${{FOO}} ${{BAR}}` where `FOO` or `BAR` come from a `regex` could not be detected at compile time.

Is there something we don't get from the current master implementation that we would get from adding `default` with `required` or `optional`?

**Comment by rvansa** [comment]
One note: right now `states` are declared on a file level, and I am not sure if these are set for the non-main files. I did not properly realize that above.

`set-state` does the job, though the imperative approach does not stick out in the script structure as declarative one. There's also duplication of the variable name when you write
```yaml
scripts:
  foo:
  - set-state: FOO ${{FOO:my-default}}
  - sh: ...
```
and some curly braces that your eyes need to parse. IMO despite a bit more verbosity it's easier to read
```yaml
scripts:
  foo:
    states:
      FOO:
        default: my-default
    commands:
    - sh: ...
```

It's true that simple `FOO: my-default` looks more like overriding that variable than just supplying the default if not set.

About the required vars: I agree with the abort; the thing is to abort as soon as possible. With declarative required variable it would fail before the first command from the script gets executed. Yes, you could have the same check doing just
```
- sh: echo ${{FOO}} > /dev/null
```
but again, it's about readability.

**Comment by johnaohara** [comment]
I think the benefit of adding `required` / `optional` allows for a fail fast path for validating state variables required for a run at startup.

> We could replace all the `${{GIT_REPO:/tmp/async-profiler}}` with a `set-state` at the start of the script

If we have multiple scripts running on multiple hosts, there is no guarantee of script ordering. We would need to add a `set-state` command to the start of every script that used that state variable to check if it was empty if we want to fail fast. Or add the the setup script, but not all qDup files will contain setup scripts.

> I think runs aborting due to missing state should already provide the desired check on required state so we don't need to add reserved words to the state json. 

I think this is a side effect of `set-state` and is not explicit behaviour of qDup, I think it would be more difficult for users to find/remember this behaviour compared to a declarative property on a state variable that could be easily documented.

> Aborting has the added benefit of catching runtime issues that cannot be detected at compile time. For example `set-state: ${{FOO}} ${{BAR}}` where `FOO` or `BAR` come from a `regex` could not be detected at compile time.

I agree that in the case of assigning dynamic state based on the result of a cmd, the onus should be on the user to verify that the  state variable contains valid data or abort.

> 
> Is there something we don't get from the current master implementation that we would get from adding `default` with `required` or `optional`?

I think we would get a succinct, more robust, fail fast error checking for variables that need to be set for a script

**Comment by willr3** [comment]
Sorry if I am being dense but what are the goals for this feature change? I'm reluctant to add reserved words but if that proves to be the best way to achieve the goals then we can certainly add them.
If our goal is to mark variables as optional or required then I think we already have that in the syntax.
```yaml
foo:
- sh: echo ${{OPTIONAL:defaultValue}} #will not fail because a default is provided
- sh: echo ${{REQUIRED}} #will fail because a default is not provided
```
There is a complaint we have about `${{OPTIONAL:defaultValue}}` and having to write the defaultValue each time. I don't think that is necessary, it was just how I wrote the scripts originally. We can either `set-state: OPTIONAL ${{OPTIONAL:defaultValue}}` or the script can add `OPTIONAL: defaultValue` to `states` and rely on the failure if it gets removed from `states`. A utility yaml can also have a `states` section which are overridden by the first yaml file in the list of yaml files to qDup.jar. I used the `${{OPTIONAL:defaultValue}}`

If our goal is to fail at build time rather than runtime when a required variable is not defined then I would like to take a try at adding that to the static analysis that runs during build time. Right now qDup does the following static analysis:
- Calculate expected signal counts for all signals
- Ensure there are no remote shell commands in an observable context. (make sure `sh` isn't called in `watch` or `on-signal` or `timeout`)
- Check for script loops
We could check for `${{FOO}}` where FOO is not in `states` and not in `set-state: FOO ...`. This would not deal with `set-state: ${{BIZ}} ...' where `BIZ=FOO` but I suspect that will be uncommon and we either add a flag to disable the static check when we know it fails incorrectly (e.g. `--disable statescan`) or a flag to ignore specific variable names (e.g. `--state-ignore FOO`)

Let me know what you guys think and I might start hacking at the static analysis because that part of the code could use a few minutes of review.

**Comment by rvansa** [comment]
The goal is improved readability and structure, opinionated places to declare input variables for each script. As you've said, the goal can be achieved with `set-state`/`echo`.

Static analysis is definitely something extra, out of scope of this issue, and would work even with the imperative syntax.

If you prefer minimal complexity over readability, so be it.

**Comment by willr3** [comment]
I re-read the thread and I think I missed the initial issue. Did you proposed adding `defaults` and `required` as a way to declare the variables for a script? The `scripts` section right now only uses the key to define the script and then the value is expected to be a sequence of commands in the script. I don't think the current yaml structure would make it possible to provide per-script information about variables. We could use the `states` section to declare the default values for all variables in the file. The `states` get loaded based on the yaml file order so the first file would define the current value of states and subsequent files could define the default values.
Another option is to introduce a more verbose way to write the yaml for the `scripts` section.
```yaml
scripts:
  - name: async-profiler
  - variables:
    - GIT_REPO: /tmp/async-profiler #provides a default
    - PASSWORD: #no default so user must provide a value
```
I think I like the idea both of `slim` and `verbose` way to write the scripts. Adding `variables` moves the existing comments into the yaml syntax which makes it easier to read and lets us include the default in the syntax but I doubt it will be more accurate. We will need to scan the script to make sure `variables` is correct.

**Comment by rvansa** [comment]
Yes, I was thinking about scripts (conceptually thinking about these as functions with parameters), though some symmetry between scripts and the global vars would be welcome.

Your example mixes lists and mappings, what you wanted is
```yaml
scripts:
- name: async-profiler
  variables:
    GIT_REPO: /tmp/async-profiler #provides a default
    PASSWORD: #no default so user must provide a value
  commands:
  - sh: ...
```
Name, variable and commands belong to single item, so these all are single mapping in the list of scripts. Also, variable mapping uses unique keys (variable names) so there's no need to put them in as a list.

One downside of the verbose way is that while the name (`async-profiler`) is unique it is not used as unique key for the scripts; if you did so you'd have to add one more level of indentation:
```yaml
scripts:
  async-profiler:
    variables:
      GIT_REPO: /tmp/async-profiler #provides a default
      PASSWORD: #no default so user must provide a value
    commands:
    - sh: ...
```

About the order of loading: to me it seems a bit confusing that you can have multiple files with host definitions etc. but actually only the first is used. I'd prefer the other files to be library-only (so these could contain only scripts - ok, maybe some global vars as well).

**Comment by rvansa** [comment]
Any updates?

**Comment by willr3** [comment]
The static analysis part is added to qDup. 
```yaml
scripts:
  test:
  - sh: echo "${{does_not_exist}}"

```
Will not start a run if `does_not_exist` is not defined
```
Error: does_not_exist is used before it appears to be set
  role: doit stage: setup script: test
  command: sh: echo "${{does_not_exist}}"
```
We don't yet have an updated yaml parser that accepts variables and associates a default value. We also need to ensure the default value gets replaced with any other value in state be it in a `with`, `set-state`, `states`, or `-S` in the command line.
