### ISSUE TITLE
Automatic abort on error

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#63]
qDup could implement behaviour similar to `set -e` in bash: with some command-line flag (or option in the script) any command that does not exit with status 0 would result in `abort` unless the exit status is handled explicitly:

```yaml
- sh: my-command ...
  onExit:
    0:
    - sh: echo success
    15:
    - abort: command terminated
    else:
    - sh: echo failed with exit value $?
```
