### ISSUE TITLE
Loop enhancements

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#65]
While it is possible to loop N times using
```yaml
- for-each: IT ${{= [...Array(${{N}}).keys()] }}
  then: ...
```
it would be convenient to have a simpler syntax, e.g.
```yaml
- for-each:
  name: IT
  range: 1 ${{N}}
  then: ...
```
where `range` is in form `?<start> <end> ?<increment>`.

Also, it would be nice to be able to break out of a loop.

**Comment by rvansa** [comment]
Ouch, the above even breaks due to whitespaces in the <values> expression - please limit the String.split to 2 parts.

**Comment by willr3** [comment]
I think this is a bug in how the yaml scalar is parsed. The Parser.split() should not split a state expression (`${{...}}`) but right now it is too simplistic. I will work on that.

**Comment by willr3** [comment]
41bb087 should fix the bug with parsing the spaces in a state pattern. 
I agree, `${{= [...Array(${{N}}).keys()] }}` is quite cumbersome when we want to use `for-each` to loop a fixed number of times.
What do you think about adding a javascript `range` method? 
We could use `${{= range(${{N}) }}` for `[0,N)`, `${{= range(1,${{N}) }}` for `[1,N)`, or `${{= range(1,${{N}},5) }}` to step by 5 each time?
I like the idea of adding the javascript method because it keeps the yaml syntax the same for the different `for-each` use cases but I do worry that it will be hard to discover unless documentation is improved. The mapping yaml for `for-each`:
```yaml
- for-each:
    name: IT
    input: ${{=range(1, ${{N}} ) }}
  then:
  ...
``` 
If we want to expand the yaml syntax to be more declarative then what do you think about adding `range` as a possible child for `input`
- for-each:
    name: IT
    input: 
      range:
        start: 1 #default would be 0
        stop: ${{N}}
        step: 5 #default would be 1
  then:
  ...
```
The Parser would convert the yaml `range` into the json array we already use internally. I am personally not a fan of the declarative approach but I agree it is worth considering.

**Comment by willr3** [comment]
*breaking out of a loop
We could add a `check` to the yaml mapping but then what should be the value of the `check`? One idea is we can use the javascript engine and check is a function that acts on the `state` and returns something `falsey` if the loop should abort.
```yaml
- for-each:
    name: IT
    input: [ 0, 1, 2, 3, 4, 5]
    check: |
      (state) -> {
        return state.foo == "OK"
      }
  then:
  ...
```
This would let us extend the supported javascript method parameters to include a snapshot of signals and counters without having to create a descriptive language for all of the possible checks we might want to perform. Perhaps something like
```yaml
- for-each: 
  ...
  check: |
    (state,signals,counters) -> {
      if(signals[${{signal_name}}].count > 0){ #more than 0 are remaining to signal
         return true;                          #continue the loop
      } else {
         return false;                         #stop the loop
      }
    }
```
