### ISSUE TITLE
State access checking failing valid script

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#70]
State access checking is failing scripts that are valid, e.g.

```
    run-permations:
      - for-each: TEST ${{TESTS}}
        then:
        - for-each: VERSION ${{QUARKUS_VERSIONS}}
          then:
          - set-state: RUN.results.${{TEST}}["${{VERSION}}"].something 1000
      - sh: echo '${{RUN.results}}' > /tmp/results.json
      - download: ${{RESULT_FILE}}
```

Will fail to run with the following message;

```
Error: results is used before it appears to be set
  role: build stage: run script: run-permations
  command: sh: echo '${{RUN.results}}' > /tmp/results.json
```

In this instance, the state is built dynamically and will be valid at the point it is accessed.  There is no branching in the script logic such that the state might not be instantiated at the point it is accessed.  So users either have to add boilerplate code to instantiate state at the start of the script or in the `states:` section

or

the error is reported as a WARN and the script is allowed to run

@willr3 wdyt?
